# Auto-generated from diagrams/uml_draft.mmd
# Do not edit this file manually -- regenerate from the UML diagram instead.

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class Owner:
    """Represents a pet owner with scheduling preferences and time constraints."""

    name: str
    availableHours: int
    preferences: List[str] = field(default_factory=list)
    constraints: Dict[str, str] = field(default_factory=dict)

    def addPreference(self, preference: str) -> None:
        """Add a scheduling preference to the owner's preference list."""
        pass

    def getPreferences(self) -> List[str]:
        """Return the full list of owner preferences."""
        pass

    def setAvailableHours(self, hours: int) -> None:
        """Update the number of hours the owner is available per day."""
        pass


@dataclass
class Pet:
    """Represents a pet with its species, age, dietary needs, and special requirements."""

    name: str
    species: str
    age: int
    specialNeeds: Dict[str, str] = field(default_factory=dict)
    dietary: Dict[str, str] = field(default_factory=dict)

    def addSpecialNeed(self, need: str, detail: str) -> None:
        """Record a special care need and its associated detail for this pet."""
        pass

    def getInfo(self) -> str:
        """Return a human-readable summary of the pet's information."""
        pass

    def getSpecies(self) -> str:
        """Return the species of this pet."""
        pass


@dataclass
class Task:
    """Represents a pet-care task with scheduling metadata and recurrence rules."""

    title: str
    durationMinutes: int
    priority: str
    description: str
    isCompleted: bool = False
    recurrence: str = ""
    startHour: int = 0

    def markComplete(self) -> None:
        """Mark this task as completed."""
        pass

    def getPriority(self) -> int:
        """Return the numeric priority level of this task."""
        pass

    def getDuration(self) -> int:
        """Return the duration of this task in minutes."""
        pass

    def isRecurring(self) -> bool:
        """Return True if this task recurs on a schedule."""
        pass

    def getNextOccurrence(self) -> datetime:
        """Calculate and return the next scheduled occurrence of this task."""
        pass


@dataclass
class ScheduledTask:
    """Wraps a Task with concrete start/end times and the scheduler's reasoning."""

    task: Task
    startTime: int
    endTime: int
    reasoning: str = ""

    def getTimeSlot(self) -> str:
        """Return a formatted string describing the scheduled time window."""
        pass


@dataclass
class Scheduler:
    """Orchestrates pet-care scheduling for an owner across one or more pets."""

    owner: Owner
    pets: List[Pet] = field(default_factory=list)
    tasks: List[Task] = field(default_factory=list)
    schedule: List[ScheduledTask] = field(default_factory=list)

    def addTask(self, task: Task) -> None:
        """Add a task to the scheduler's task list."""
        pass

    def removeTask(self, taskId: str) -> None:
        """Remove a task from the scheduler's task list by its identifier."""
        pass

    def generateSchedule(self, dayHours: int) -> List[ScheduledTask]:
        """Generate a full day's schedule given the number of available hours."""
        pass

    def sortTasks(self) -> List[Task]:
        """Return tasks sorted by priority and other scheduling criteria."""
        pass

    def filterByTimeAvailable(self) -> List[Task]:
        """Return only the tasks that fit within the owner's available hours."""
        pass

    def handleConflicts(self) -> List[ScheduledTask]:
        """Resolve any scheduling conflicts and return a conflict-free schedule."""
        pass

    def expandRecurringTasks(self) -> List[Task]:
        """Expand recurring tasks into individual instances for the current day."""
        pass

    def explainSchedule(self) -> str:
        """Return a human-readable explanation of the generated schedule."""
        pass

    def getReasoningFor(self, task: Task) -> str:
        """Return the scheduler's reasoning for how a specific task was placed."""
        pass