# Auto-generated from diagrams/uml_draft.mmd
# Do not edit this file manually -- regenerate from the UML diagram instead.

from __future__ import annotations

from dataclasses import dataclass, field, replace
from datetime import datetime, timedelta
from typing import Dict, List, Optional


@dataclass
class Owner:
    """Represents a pet owner with scheduling preferences and time constraints."""

    name: str
    availableHours: int
    preferences: List[str] = field(default_factory=list)
    constraints: Dict[str, str] = field(default_factory=dict)
    pets: List[Pet] = field(default_factory=list)
    tasks: List[Task] = field(default_factory=list)

    def addPreference(self, preference: str) -> None:
        """Add a scheduling preference to the owner's preference list."""
        if preference not in self.preferences:
            self.preferences.append(preference)

    def getPreferences(self) -> List[str]:
        """Return the full list of owner preferences."""
        return self.preferences

    def setAvailableHours(self, hours: int) -> None:
        """Update the number of hours the owner is available per day."""
        self.availableHours = max(0, hours)

    def addTask(self, task: Task) -> None:
        """Add a task to the owner's master task list."""
        self.tasks.append(task)

    def completeTask(self, taskTitle: str) -> Optional[Task]:
        """Mark a task as completed; re-add the next occurrence if recurring."""
        for task in self.tasks:
            if task.title == taskTitle:
                next_task = task.markComplete()
                self.tasks.remove(task)
                if next_task:
                    self.tasks.append(next_task)
                return next_task
        return None

    def getTodoList(self) -> List[Task]:
        """Return all pending (incomplete) tasks."""
        return [t for t in self.tasks if not t.isCompleted]


@dataclass
class Pet:
    """Represents a pet with its species, age, dietary needs, and special requirements."""

    name: str
    species: str
    age: int
    specialNeeds: Dict[str, str] = field(default_factory=dict)
    dietary: Dict[str, str] = field(default_factory=dict)

    def addSpecialNeed(self, need: str, detail: str) -> None:
        """Record a special care need and its associated detail for this pet."""
        self.specialNeeds[need] = detail

    def getInfo(self) -> str:
        """Return a human-readable summary of the pet's information."""
        info = f"{self.name} ({self.species}, {self.age} years old)"
        if self.specialNeeds:
            info += f"\nSpecial needs: {', '.join(f'{k}: {v}' for k, v in self.specialNeeds.items())}"
        if self.dietary:
            info += f"\nDietary: {', '.join(f'{k}: {v}' for k, v in self.dietary.items())}"
        return info

    def getSpecies(self) -> str:
        """Return the species of this pet."""
        return self.species


@dataclass
class Task:
    """Represents a pet-care task with scheduling metadata and recurrence rules."""

    title: str
    durationMinutes: int
    priority: int
    description: str
    isCompleted: bool = False
    recurrence: str = ""
    startTime: str = "00:00"
    dueDate: Optional[datetime] = None
    appliesTo: List[Pet] = field(default_factory=list)

    def markComplete(self) -> Optional["Task"]:
        """Mark this task as completed; return the next occurrence for daily/weekly tasks."""
        self.isCompleted = True
        if not self.isRecurring():
            return None

        base = self.dueDate if self.dueDate else datetime.now()
        recurrence_lower = self.recurrence.lower()

        if "daily" in recurrence_lower:
            next_due = base + timedelta(days=1)
        elif "weekly" in recurrence_lower:
            next_due = base + timedelta(weeks=1)
        else:
            return None

        return replace(self, isCompleted=False, dueDate=next_due)

    def getPriority(self) -> int:
        """Return the numeric priority level of this task."""
        return self.priority

    def getDuration(self) -> int:
        """Return the duration of this task in minutes."""
        return self.durationMinutes

    def isRecurring(self) -> bool:
        """Return True if this task recurs on a schedule."""
        return bool(self.recurrence and self.recurrence.lower() != "once")

    def getNextOccurrence(self) -> datetime:
        """Calculate and return the next scheduled occurrence of this task."""
        now = datetime.now()

        hour, minute = (int(x) for x in self.startTime.split(":"))

        if not self.isRecurring():
            return now.replace(hour=hour, minute=minute, second=0, microsecond=0)

        recurrence_lower = self.recurrence.lower()
        if "daily" in recurrence_lower:
            next_time = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
            if next_time <= now:
                next_time += timedelta(days=1)
        elif "weekly" in recurrence_lower:
            next_time = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
            if next_time <= now:
                next_time += timedelta(weeks=1)
        elif "monthly" in recurrence_lower:
            next_time = now.replace(hour=hour, minute=minute, second=0, microsecond=0, day=1)
            if next_time <= now:
                if now.month == 12:
                    next_time = next_time.replace(year=now.year + 1, month=1)
                else:
                    next_time = next_time.replace(month=now.month + 1)
        else:
            next_time = now.replace(hour=hour, minute=minute, second=0, microsecond=0)

        return next_time


@dataclass
class ScheduledTask:
    """Wraps a Task with concrete start/end times and the scheduler's reasoning."""

    task: Task
    pet: Pet
    startTime: int
    endTime: int
    reasoning: str = ""

    def getTimeSlot(self) -> str:
        """Return a formatted string describing the scheduled time window."""
        return f"{self.startTime:02d}:00 - {self.endTime:02d}:00"


@dataclass
class Scheduler:
    """Orchestrates pet-care scheduling for an owner across one or more pets."""

    owner: Owner
    pets: List[Pet] = field(default_factory=list)
    tasks: List[Task] = field(default_factory=list)
    schedule: List[ScheduledTask] = field(default_factory=list)

    def loadTasksFromOwner(self) -> List[Task]:
        """Retrieve all tasks from the owner's master task list."""
        self.tasks = self.owner.tasks
        return self.tasks

    def addTask(self, task: Task) -> None:
        """Add a task to the scheduler's task list."""
        self.tasks.append(task)

    def removeTask(self, taskId: str) -> None:
        """Remove a task from the scheduler's task list by its identifier."""
        self.tasks = [t for t in self.tasks if t.title != taskId]

    def sortTasks(self) -> List[Task]:
        """Return tasks sorted by priority and other scheduling criteria."""
        return sorted(
            self.tasks,
            key=lambda t: (t.getPriority(), t.startTime, -t.durationMinutes)
        )

    def sort_by_time(self) -> List[Task]:
        """Return tasks sorted by scheduled time (HH:MM string), then by priority.

        HH:MM strings are zero-padded, so lexicographic order == chronological order:
          "07:00" < "08:30" < "14:00" — no datetime parsing needed.
        """
        return sorted(self.tasks, key=lambda t: (t.startTime, t.priority))

    def filterTasks(
        self,
        completed: Optional[bool] = None,
        pet_name: Optional[str] = None,
    ) -> List[Task]:
        """Filter tasks by completion status and/or the name of the pet they apply to."""
        result = self.tasks
        if completed is not None:
            result = [t for t in result if t.isCompleted == completed]
        if pet_name is not None:
            result = [t for t in result if any(p.name == pet_name for p in t.appliesTo)]
        return result

    def filterByTimeAvailable(self) -> List[Task]:
        """Return only the tasks that fit within the owner's available hours."""
        available_minutes = self.owner.availableHours * 60
        total_duration = 0
        filtered_tasks = []

        for task in self.sortTasks():
            if total_duration + task.durationMinutes <= available_minutes:
                filtered_tasks.append(task)
                total_duration += task.durationMinutes

        return filtered_tasks

    def expandRecurringTasks(self) -> List[Task]:
        """Expand recurring tasks into individual instances for the current day."""
        expanded = []
        for task in self.tasks:
            if task.isRecurring():
                expanded.append(task)
            else:
                expanded.append(task)
        return expanded

    def handleConflicts(self) -> List[ScheduledTask]:
        """Resolve any scheduling conflicts and return a conflict-free schedule."""
        if not self.schedule:
            return []

        resolved = []
        current_hour = 0

        for scheduled in sorted(self.schedule, key=lambda s: s.startTime):
            if scheduled.startTime < current_hour:
                scheduled.startTime = current_hour
                scheduled.endTime = scheduled.startTime + (scheduled.task.durationMinutes // 60)

            current_hour = scheduled.endTime
            resolved.append(scheduled)

        self.schedule = resolved
        return resolved

    def generateSchedule(self, dayHours: int) -> List[ScheduledTask]:
        """Generate a full day's schedule given the number of available hours."""
        self.schedule = []
        filtered_tasks = self.filterByTimeAvailable()

        current_hour = 0
        max_hours = min(dayHours, self.owner.availableHours)

        for task in filtered_tasks:
            if task.isCompleted:
                continue

            duration_hours = max(1, task.durationMinutes // 60)

            if current_hour + duration_hours <= max_hours:
                scheduled = ScheduledTask(
                    task=task,
                    pet=task.appliesTo[0] if task.appliesTo else self.pets[0] if self.pets else Pet("Unknown", "Unknown", 0),
                    startTime=current_hour,
                    endTime=current_hour + duration_hours,
                    reasoning=f"Scheduled based on {task.priority} priority"
                )
                self.schedule.append(scheduled)
                current_hour += duration_hours

        self.handleConflicts()
        return self.schedule

    def detectConflicts(self) -> List[str]:
        """Return warning messages for any tasks whose time windows overlap.

        Two tasks conflict when their [start, start+duration) intervals intersect.
        Same-pet overlaps are flagged as pet conflicts; different-pet overlaps are
        flagged as owner-time conflicts (the owner can only do one thing at a time).
        Returns an empty list when no conflicts exist — never raises.
        """
        from itertools import combinations

        def _parse(task: Task):
            h, m = task.startTime.split(":")
            start = int(h) * 60 + int(m)
            return start, start + task.durationMinutes

        def fmt(minutes: int) -> str:
            return f"{minutes // 60:02d}:{minutes % 60:02d}"

        parsed = [(task, *_parse(task)) for task in self.tasks]
        warnings: List[str] = []

        for (a, start_a, end_a), (b, start_b, end_b) in combinations(parsed, 2):

            if start_a < end_b and start_b < end_a:
                shared = {p.name for p in a.appliesTo} & {p.name for p in b.appliesTo}
                kind = f"same pet — {', '.join(sorted(shared))}" if shared else "owner time"
                warnings.append(
                    f"[CONFLICT — {kind}] '{a.title}' and '{b.title}' "
                    f"overlap ({a.startTime}-{fmt(end_a)} vs {b.startTime}-{fmt(end_b)})"
                )

        return warnings

    def explainSchedule(self) -> str:
        """Return a human-readable explanation of the generated schedule."""
        if not self.schedule:
            return f"No tasks scheduled for {self.owner.name}."

        explanation = f"Daily schedule for {self.owner.name} ({self.owner.availableHours} hours available):\n\n"

        for scheduled in sorted(self.schedule, key=lambda s: s.startTime):
            priority_label = {1: "High", 2: "Medium", 3: "Low"}.get(scheduled.task.priority, "Unknown")
            explanation += f"⏰ {scheduled.getTimeSlot()}: {scheduled.task.title} ({scheduled.pet.name})\n"
            explanation += f"   Duration: {scheduled.task.durationMinutes} minutes | Priority: {priority_label}\n"
            explanation += f"   Reason: {scheduled.reasoning}\n\n"

        return explanation